version: '3.7'

services:
  api:
    container_name: api
    build:
      context: src/.
      dockerfile: Dockerfile.api
    dns:
      - 8.8.8.8
    ports:
      - '5000:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  console-client:
    container_name: console
    build:
      context: src/.
      dockerfile: Dockerfile.console
    environment:
      - SignalRSettings__BaseUrl=http://api:80/
    depends_on:
      - api

  test:
    container_name: test
    build:
      context: src/.
      dockerfile: Dockerfile.test
    environment:
      - APP_URI=http://api:80/
    depends_on:
      - api
