/*
 * Competition Status API
 *
 * API which provides status information for sports competition.                          See https://github.com/Hekku2/competition-status-server/ for more information.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents a competitor or competitors (if doubles or other team  activity) who participate in division. This class describes what is the  status of their participation in the division.
    /// </summary>
    [DataContract(Name = "CompetitorPositionFileModel")]
    public partial class CompetitorPositionFileModel : IEquatable<CompetitorPositionFileModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompetitorPositionFileModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CompetitorPositionFileModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CompetitorPositionFileModel" /> class.
        /// </summary>
        /// <param name="id">Unique ID for these competitors. This is asystem ID, which is used  to set the competitor(s) as active competitor.  NOTE: This is not the same as a jersey number etc. (required).</param>
        /// <param name="competitors">Competitors, should have at least one entity. (required).</param>
        /// <param name="forfeit">If true, competitors are shown as forfeited for this division.    In this context, forfeit can happen if:  a) Competitor doesn&#39;t show up for competition  b) Competitor gets injured and is unable to continue  c) Competitor is disqualified    This doesn&#39;t care if it&#39;s competitor&#39;s fault or not, this just  means that competitors score is not shown.    This means following:  a) Results are not shown, if given.  b) These competitors are not shown schedule.  c) When listed, competitors are shown in the bottom part of the  listing. (required).</param>
        /// <param name="results">results.</param>
        public CompetitorPositionFileModel(int id = default(int), List<CompetitorFileModel> competitors = default(List<CompetitorFileModel>), bool forfeit = default(bool), PoleResultFileModel results = default(PoleResultFileModel))
        {
            this.Id = id;
            // to ensure "competitors" is required (not null)
            if (competitors == null) {
                throw new ArgumentNullException("competitors is a required property for CompetitorPositionFileModel and cannot be null");
            }
            this.Competitors = competitors;
            this.Forfeit = forfeit;
            this.Results = results;
        }

        /// <summary>
        /// Unique ID for these competitors. This is asystem ID, which is used  to set the competitor(s) as active competitor.  NOTE: This is not the same as a jersey number etc.
        /// </summary>
        /// <value>Unique ID for these competitors. This is asystem ID, which is used  to set the competitor(s) as active competitor.  NOTE: This is not the same as a jersey number etc.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Competitors, should have at least one entity.
        /// </summary>
        /// <value>Competitors, should have at least one entity.</value>
        [DataMember(Name = "competitors", IsRequired = true, EmitDefaultValue = false)]
        public List<CompetitorFileModel> Competitors { get; set; }

        /// <summary>
        /// If true, competitors are shown as forfeited for this division.    In this context, forfeit can happen if:  a) Competitor doesn&#39;t show up for competition  b) Competitor gets injured and is unable to continue  c) Competitor is disqualified    This doesn&#39;t care if it&#39;s competitor&#39;s fault or not, this just  means that competitors score is not shown.    This means following:  a) Results are not shown, if given.  b) These competitors are not shown schedule.  c) When listed, competitors are shown in the bottom part of the  listing.
        /// </summary>
        /// <value>If true, competitors are shown as forfeited for this division.    In this context, forfeit can happen if:  a) Competitor doesn&#39;t show up for competition  b) Competitor gets injured and is unable to continue  c) Competitor is disqualified    This doesn&#39;t care if it&#39;s competitor&#39;s fault or not, this just  means that competitors score is not shown.    This means following:  a) Results are not shown, if given.  b) These competitors are not shown schedule.  c) When listed, competitors are shown in the bottom part of the  listing.</value>
        [DataMember(Name = "forfeit", IsRequired = true, EmitDefaultValue = true)]
        public bool Forfeit { get; set; }

        /// <summary>
        /// Gets or Sets Results
        /// </summary>
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public PoleResultFileModel Results { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompetitorPositionFileModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Competitors: ").Append(Competitors).Append("\n");
            sb.Append("  Forfeit: ").Append(Forfeit).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CompetitorPositionFileModel);
        }

        /// <summary>
        /// Returns true if CompetitorPositionFileModel instances are equal
        /// </summary>
        /// <param name="input">Instance of CompetitorPositionFileModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CompetitorPositionFileModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.Competitors == input.Competitors ||
                    this.Competitors != null &&
                    input.Competitors != null &&
                    this.Competitors.SequenceEqual(input.Competitors)
                ) && 
                (
                    this.Forfeit == input.Forfeit ||
                    this.Forfeit.Equals(input.Forfeit)
                ) && 
                (
                    this.Results == input.Results ||
                    (this.Results != null &&
                    this.Results.Equals(input.Results))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.Competitors != null)
                {
                    hashCode = (hashCode * 59) + this.Competitors.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Forfeit.GetHashCode();
                if (this.Results != null)
                {
                    hashCode = (hashCode * 59) + this.Results.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
