/*
 * Competition Status API
 *
 * API which provides status information for sports competition.                          See https://github.com/Hekku2/competition-status-server/ for more information.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents current competitor who is performing or performing next  when no other competitor is not active.
    /// </summary>
    [DataContract(Name = "CurrentCompetitorContentModel")]
    public partial class CurrentCompetitorContentModel : IEquatable<CurrentCompetitorContentModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentCompetitorContentModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CurrentCompetitorContentModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentCompetitorContentModel" /> class.
        /// </summary>
        /// <param name="division">Division of competitor(s). This should match some division in active  competition (required).</param>
        /// <param name="competitors">Competitor(s). This should have at least one value, but may have  multiple values if there are multiple persons performing for single  performance. (required).</param>
        public CurrentCompetitorContentModel(string division = default(string), List<CompetitorModel> competitors = default(List<CompetitorModel>))
        {
            // to ensure "division" is required (not null)
            if (division == null) {
                throw new ArgumentNullException("division is a required property for CurrentCompetitorContentModel and cannot be null");
            }
            this.Division = division;
            // to ensure "competitors" is required (not null)
            if (competitors == null) {
                throw new ArgumentNullException("competitors is a required property for CurrentCompetitorContentModel and cannot be null");
            }
            this.Competitors = competitors;
        }

        /// <summary>
        /// Division of competitor(s). This should match some division in active  competition
        /// </summary>
        /// <value>Division of competitor(s). This should match some division in active  competition</value>
        [DataMember(Name = "division", IsRequired = true, EmitDefaultValue = false)]
        public string Division { get; set; }

        /// <summary>
        /// Competitor(s). This should have at least one value, but may have  multiple values if there are multiple persons performing for single  performance.
        /// </summary>
        /// <value>Competitor(s). This should have at least one value, but may have  multiple values if there are multiple persons performing for single  performance.</value>
        [DataMember(Name = "competitors", IsRequired = true, EmitDefaultValue = false)]
        public List<CompetitorModel> Competitors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CurrentCompetitorContentModel {\n");
            sb.Append("  Division: ").Append(Division).Append("\n");
            sb.Append("  Competitors: ").Append(Competitors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CurrentCompetitorContentModel);
        }

        /// <summary>
        /// Returns true if CurrentCompetitorContentModel instances are equal
        /// </summary>
        /// <param name="input">Instance of CurrentCompetitorContentModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CurrentCompetitorContentModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Division == input.Division ||
                    (this.Division != null &&
                    this.Division.Equals(input.Division))
                ) && 
                (
                    this.Competitors == input.Competitors ||
                    this.Competitors != null &&
                    input.Competitors != null &&
                    this.Competitors.SequenceEqual(input.Competitors)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Division != null)
                {
                    hashCode = (hashCode * 59) + this.Division.GetHashCode();
                }
                if (this.Competitors != null)
                {
                    hashCode = (hashCode * 59) + this.Competitors.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
