/*
 * Competition Status API
 *
 * API which provides status information for sports competition.                          See https://github.com/Hekku2/competition-status-server/ for more information.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Describes division that is saved in file. User for JSON conversions.
    /// </summary>
    [DataContract(Name = "DivisionFileModel")]
    public partial class DivisionFileModel : IEquatable<DivisionFileModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DivisionFileModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DivisionFileModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DivisionFileModel" /> class.
        /// </summary>
        /// <param name="name">Name of the division. (required).</param>
        /// <param name="items">Competitors participating in this division. (required).</param>
        public DivisionFileModel(string name = default(string), List<CompetitorPositionFileModel> items = default(List<CompetitorPositionFileModel>))
        {
            // to ensure "name" is required (not null)
            if (name == null) {
                throw new ArgumentNullException("name is a required property for DivisionFileModel and cannot be null");
            }
            this.Name = name;
            // to ensure "items" is required (not null)
            if (items == null) {
                throw new ArgumentNullException("items is a required property for DivisionFileModel and cannot be null");
            }
            this.Items = items;
        }

        /// <summary>
        /// Name of the division.
        /// </summary>
        /// <value>Name of the division.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Competitors participating in this division.
        /// </summary>
        /// <value>Competitors participating in this division.</value>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = false)]
        public List<CompetitorPositionFileModel> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DivisionFileModel {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DivisionFileModel);
        }

        /// <summary>
        /// Returns true if DivisionFileModel instances are equal
        /// </summary>
        /// <param name="input">Instance of DivisionFileModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DivisionFileModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Items == input.Items ||
                    this.Items != null &&
                    input.Items != null &&
                    this.Items.SequenceEqual(input.Items)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Items != null)
                {
                    hashCode = (hashCode * 59) + this.Items.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
