/*
 * Competition Status API
 *
 * API which provides status information for sports competition.                          See https://github.com/Hekku2/competition-status-server/ for more information.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Describes a result for competitor(s) in for a single performance and what  place it did achieve, if any.
    /// </summary>
    [DataContract(Name = "PerformanceResultsContentModel")]
    public partial class PerformanceResultsContentModel : IEquatable<PerformanceResultsContentModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PerformanceResultsContentModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PerformanceResultsContentModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PerformanceResultsContentModel" /> class.
        /// </summary>
        /// <param name="division">Name of the division. Should match some division in currenlty active  competition. (required).</param>
        /// <param name="currentPlace">Placement that the competitor(s) received with this result. This is null  If current place couldn&#39;t be calculated.  Starts from 1..</param>
        /// <param name="competitors">Competitors that did the performance. This should contain at least one  item. (required).</param>
        /// <param name="result">result (required).</param>
        public PerformanceResultsContentModel(string division = default(string), int? currentPlace = default(int?), List<CompetitorModel> competitors = default(List<CompetitorModel>), PoleSportResultModel result = default(PoleSportResultModel))
        {
            // to ensure "division" is required (not null)
            if (division == null) {
                throw new ArgumentNullException("division is a required property for PerformanceResultsContentModel and cannot be null");
            }
            this.Division = division;
            // to ensure "competitors" is required (not null)
            if (competitors == null) {
                throw new ArgumentNullException("competitors is a required property for PerformanceResultsContentModel and cannot be null");
            }
            this.Competitors = competitors;
            // to ensure "result" is required (not null)
            if (result == null) {
                throw new ArgumentNullException("result is a required property for PerformanceResultsContentModel and cannot be null");
            }
            this.Result = result;
            this.CurrentPlace = currentPlace;
        }

        /// <summary>
        /// Name of the division. Should match some division in currenlty active  competition.
        /// </summary>
        /// <value>Name of the division. Should match some division in currenlty active  competition.</value>
        [DataMember(Name = "division", IsRequired = true, EmitDefaultValue = false)]
        public string Division { get; set; }

        /// <summary>
        /// Placement that the competitor(s) received with this result. This is null  If current place couldn&#39;t be calculated.  Starts from 1.
        /// </summary>
        /// <value>Placement that the competitor(s) received with this result. This is null  If current place couldn&#39;t be calculated.  Starts from 1.</value>
        [DataMember(Name = "currentPlace", EmitDefaultValue = true)]
        public int? CurrentPlace { get; set; }

        /// <summary>
        /// Competitors that did the performance. This should contain at least one  item.
        /// </summary>
        /// <value>Competitors that did the performance. This should contain at least one  item.</value>
        [DataMember(Name = "competitors", IsRequired = true, EmitDefaultValue = false)]
        public List<CompetitorModel> Competitors { get; set; }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [DataMember(Name = "result", IsRequired = true, EmitDefaultValue = false)]
        public PoleSportResultModel Result { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PerformanceResultsContentModel {\n");
            sb.Append("  Division: ").Append(Division).Append("\n");
            sb.Append("  CurrentPlace: ").Append(CurrentPlace).Append("\n");
            sb.Append("  Competitors: ").Append(Competitors).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PerformanceResultsContentModel);
        }

        /// <summary>
        /// Returns true if PerformanceResultsContentModel instances are equal
        /// </summary>
        /// <param name="input">Instance of PerformanceResultsContentModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PerformanceResultsContentModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Division == input.Division ||
                    (this.Division != null &&
                    this.Division.Equals(input.Division))
                ) && 
                (
                    this.CurrentPlace == input.CurrentPlace ||
                    (this.CurrentPlace != null &&
                    this.CurrentPlace.Equals(input.CurrentPlace))
                ) && 
                (
                    this.Competitors == input.Competitors ||
                    this.Competitors != null &&
                    input.Competitors != null &&
                    this.Competitors.SequenceEqual(input.Competitors)
                ) && 
                (
                    this.Result == input.Result ||
                    (this.Result != null &&
                    this.Result.Equals(input.Result))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Division != null)
                {
                    hashCode = (hashCode * 59) + this.Division.GetHashCode();
                }
                if (this.CurrentPlace != null)
                {
                    hashCode = (hashCode * 59) + this.CurrentPlace.GetHashCode();
                }
                if (this.Competitors != null)
                {
                    hashCode = (hashCode * 59) + this.Competitors.GetHashCode();
                }
                if (this.Result != null)
                {
                    hashCode = (hashCode * 59) + this.Result.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
