/*
 * Competition Status API
 *
 * API which provides status information for sports competition.                          See https://github.com/Hekku2/competition-status-server/ for more information.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ScoreboardSettingsFileModel
    /// </summary>
    [DataContract(Name = "ScoreboardSettingsFileModel")]
    public partial class ScoreboardSettingsFileModel : IEquatable<ScoreboardSettingsFileModel>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets ScoreboardMode
        /// </summary>
        [DataMember(Name = "scoreboardMode", EmitDefaultValue = false)]
        public ScoreboardMode? ScoreboardMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScoreboardSettingsFileModel" /> class.
        /// </summary>
        /// <param name="scoreboardMode">scoreboardMode.</param>
        /// <param name="activeDivision">Name of the currently selected division.</param>
        /// <param name="activeResult">activeResult.</param>
        public ScoreboardSettingsFileModel(ScoreboardMode? scoreboardMode = default(ScoreboardMode?), string activeDivision = default(string), int? activeResult = default(int?))
        {
            this.ScoreboardMode = scoreboardMode;
            this.ActiveDivision = activeDivision;
            this.ActiveResult = activeResult;
        }

        /// <summary>
        /// Name of the currently selected division
        /// </summary>
        /// <value>Name of the currently selected division</value>
        [DataMember(Name = "activeDivision", EmitDefaultValue = true)]
        public string ActiveDivision { get; set; }

        /// <summary>
        /// Gets or Sets ActiveResult
        /// </summary>
        [DataMember(Name = "activeResult", EmitDefaultValue = true)]
        public int? ActiveResult { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ScoreboardSettingsFileModel {\n");
            sb.Append("  ScoreboardMode: ").Append(ScoreboardMode).Append("\n");
            sb.Append("  ActiveDivision: ").Append(ActiveDivision).Append("\n");
            sb.Append("  ActiveResult: ").Append(ActiveResult).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScoreboardSettingsFileModel);
        }

        /// <summary>
        /// Returns true if ScoreboardSettingsFileModel instances are equal
        /// </summary>
        /// <param name="input">Instance of ScoreboardSettingsFileModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScoreboardSettingsFileModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ScoreboardMode == input.ScoreboardMode ||
                    this.ScoreboardMode.Equals(input.ScoreboardMode)
                ) && 
                (
                    this.ActiveDivision == input.ActiveDivision ||
                    (this.ActiveDivision != null &&
                    this.ActiveDivision.Equals(input.ActiveDivision))
                ) && 
                (
                    this.ActiveResult == input.ActiveResult ||
                    (this.ActiveResult != null &&
                    this.ActiveResult.Equals(input.ActiveResult))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ScoreboardMode.GetHashCode();
                if (this.ActiveDivision != null)
                {
                    hashCode = (hashCode * 59) + this.ActiveDivision.GetHashCode();
                }
                if (this.ActiveResult != null)
                {
                    hashCode = (hashCode * 59) + this.ActiveResult.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
