/*
 * Competition Status API
 *
 * API which provides status information for sports competition.                          See https://github.com/Hekku2/competition-status-server/ for more information.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// This desribes the mode that the scoreboard should be in.
    /// </summary>
    /// <value>This desribes the mode that the scoreboard should be in.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ScoreboardModeModel
    {
        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown = 1,

        /// <summary>
        /// Enum DivisionStatus for value: DivisionStatus
        /// </summary>
        [EnumMember(Value = "DivisionStatus")]
        DivisionStatus = 2,

        /// <summary>
        /// Enum CompetitorResults for value: CompetitorResults
        /// </summary>
        [EnumMember(Value = "CompetitorResults")]
        CompetitorResults = 3,

        /// <summary>
        /// Enum UpcomingCompetitors for value: UpcomingCompetitors
        /// </summary>
        [EnumMember(Value = "UpcomingCompetitors")]
        UpcomingCompetitors = 4

    }

}
