FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /source

COPY Api/. ./Api/
COPY Api.Models/. ./Api.Models/
COPY DataAccess/. ./DataAccess/
COPY AcceptanceTests/. ./AcceptanceTests/
COPY Org.OpenAPITools/. ./Org.OpenAPITools/

WORKDIR /source/

CMD ["dotnet", "test", "./AcceptanceTests/"]
